#!/bin/bash

echo "This script can make any of the files in this directory private."
echo "Enter the number of the file you want to protect:"

search_term=$1
processes=($(ps | grep ${search_term} | awk '{print $4} - {print $5} - {print $6} - {print $7}'))

select FILENAME in ${processes[*]};
do
     echo "You picked $FILENAME ($REPLY), it is now only accessible to you."
     chmod go-rwx "$FILENAME"
done
